In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("raw_data.csv")

In [3]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [4]:
df1 = pd.DataFrame({
    "id":[11, 12, 24],
    "name":["Carlos Morrish", "Meadul Islam", "Javed"]
})

In [9]:
pd.concat([df, df1])#row wise concatination (top of each other)
pd.concat([df, df1], ignore_index=True)

    id            name   age country   gender   income
0    1        John Doe  29.0     USA     Male  55000.0
1    1        John Doe  29.0     USA     Male  55000.0
2    2      Jane Smith   NaN  Canada   Female  62000.0
3    3            Alex   NaN     USA  Unknown  47000.0
4    4    Maria Garcia  34.0   Spain   Female      NaN
5    5          Li Wei  27.0   China     Male  51000.0
6    6             NaN  45.0   India   Female  73000.0
7    7      Ahmed Khan  38.0     NaN     Male  68000.0
8    8      Rachel Lee  29.0     USA   Female  62000.0
9    9     Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10     Emily Davis  31.0     USA      NaN  58000.0
11  11  Carlos Morrish   NaN     NaN      NaN      NaN
12  12    Meadul Islam   NaN     NaN      NaN      NaN
13  24           Javed   NaN     NaN      NaN      NaN

In [12]:
pd.concat([df, df1], axis=1)#column wise concatination (side by side)

    id          name   age country   gender   income    id            name
0    1      John Doe  29.0     USA     Male  55000.0  11.0  Carlos Morrish
1    1      John Doe  29.0     USA     Male  55000.0  12.0    Meadul Islam
2    2    Jane Smith   NaN  Canada   Female  62000.0  24.0           Javed
3    3          Alex   NaN     USA  Unknown  47000.0   NaN             NaN
4    4  Maria Garcia  34.0   Spain   Female      NaN   NaN             NaN
5    5        Li Wei  27.0   China     Male  51000.0   NaN             NaN
6    6           NaN  45.0   India   Female  73000.0   NaN             NaN
7    7    Ahmed Khan  38.0     NaN     Male  68000.0   NaN             NaN
8    8    Rachel Lee  29.0     USA   Female  62000.0   NaN             NaN
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0   NaN             NaN
10  10   Emily Davis  31.0     USA      NaN  58000.0   NaN             NaN