In [1]:
import pandas as pd
df = pd.read_csv("raw_data.csv")

In [8]:
df.groupby("country")["income"].mean()#group by country and calculate mean income
df.groupby("country")["income"].max()
df.groupby("country")["income"].min()

country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         NaN
USA       47000.0
Name: income, dtype: float64

In [6]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [11]:
df.groupby("gender")["income"].mean()
df.groupby("gender")["income"].max()
df.groupby("gender")["income"].min()

gender
Female     62000.0
Male       45000.0
Unknown    47000.0
Name: income, dtype: float64

In [16]:
df.groupby("country")["income"].agg(["mean", "max", "min"])#aggregate
df.groupby("country")["income"].aggregate(["mean", "max", "min"])#aggregate

            mean      max      min
country
Canada   62000.0  62000.0  62000.0
China    51000.0  51000.0  51000.0
India    73000.0  73000.0  73000.0
Mexico   45000.0  45000.0  45000.0
Spain        NaN      NaN      NaN
USA      55400.0  62000.0  47000.0

In [18]:
df.groupby("country")["income"].agg(mean_salary="mean", max_salary="max", min_salary="min")

         mean_salary  max_salary  min_salary
country
Canada       62000.0     62000.0     62000.0
China        51000.0     51000.0     51000.0
India        73000.0     73000.0     73000.0
Mexico       45000.0     45000.0     45000.0
Spain            NaN         NaN         NaN
USA          55400.0     62000.0     47000.0

In [37]:
# df.groupby("country").agg({
#     "income":"mean",
#     "age":"mean"
# })
df.groupby("country").agg({
    "income":"max",
    "age":"mean"
})

          income   age
country
Canada   62000.0   NaN
China    51000.0  27.0
India    73000.0  45.0
Mexico   45000.0   NaN
Spain        NaN  34.0
USA      62000.0  29.5

In [38]:
df.groupby("country").agg(
    max_income= ("income","max"),
    min_income= ("income","min"),
    avg_age=("age","mean"),
    min_age=("age","min"))

         max_income  min_income  avg_age  min_age
country
Canada      62000.0     62000.0      NaN      NaN
China       51000.0     51000.0     27.0     27.0
India       73000.0     73000.0     45.0     45.0
Mexico      45000.0     45000.0      NaN      NaN
Spain           NaN         NaN     34.0     34.0
USA         62000.0     47000.0     29.5     29.0