In [1]:
import pandas as pd

In [3]:
df_customers = pd.DataFrame({
    "customer_id":[1,2,3,4],
    "name":["Bob","Alice","Charlie","Dave"]
})

In [4]:
df_orders = pd.DataFrame({
    "order_id":[102,103,104,105],
    "customer_id":[2,1,4,5],
    "amount":[250,235,580,987],
})

In [5]:
df_customers

   customer_id     name
0            1      Bob
1            2    Alice
2            3  Charlie
3            4     Dave

In [6]:
df_orders

   order_id  customer_id  amount
0       102            2     250
1       103            1     235
2       104            4     580
3       105            5     987

In [9]:
pd.merge(df_customers, df_orders, on="customer_id")#inner join

   customer_id   name  order_id  amount
0            1    Bob       103     235
1            2  Alice       102     250
2            4   Dave       104     580

In [10]:
pd.merge(df_customers, df_orders, on="customer_id", how="left")#left join

   customer_id     name  order_id  amount
0            1      Bob     103.0   235.0
1            2    Alice     102.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     104.0   580.0

In [11]:
pd.merge(df_customers, df_orders, on="customer_id", how="right")#right join

   customer_id   name  order_id  amount
0            2  Alice       102     250
1            1    Bob       103     235
2            4   Dave       104     580
3            5    NaN       105     987

In [12]:
pd.merge(df_customers, df_orders, on="customer_id", how="outer")#outer join

   customer_id     name  order_id  amount
0            1      Bob     103.0   235.0
1            2    Alice     102.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     104.0   580.0
4            5      NaN     105.0   987.0